"""Inbound port for project management."""
from __future__ import annotations
from typing import TYPE_CHECKING, Optional, Protocol, runtime_checkable
if TYPE_CHECKING:
    from backend.src.core.entities.project import Project


@runtime_checkable
class ManageProjectUseCase(Protocol):
    async def create_project(self, filename: str, upload_path: str) -> Project: ...
    async def get_project(self, project_id: str) -> Optional[Project]: ...
    async def list_projects(self) -> list[Project]: ...
    async def delete_project(self, project_id: str) -> None: ...
    async def get_project_status(self, project_id: str) -> dict: ...
