"""Inbound port for querying experiment metrics."""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class QueryMetricsUseCase(Protocol):
    async def get_experiment_results(self, experiment_id: str) -> dict: ...
    async def get_convergence_data(self, experiment_id: str) -> list[dict]: ...
    async def get_parameter_importance(self, experiment_id: str) -> dict: ...
    async def compare_experiments(self, experiment_ids: list[str]) -> dict: ...
