"""Port for audio processing operations."""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class AudioProcessingPort(Protocol):
    def normalize_audio(self, input_path: str, output_path: str) -> str: ...
    def enhance_game_audio(self, input_path: str, output_path: str) -> str: ...
    def add_background_music(self, video_path: str, music_path: str, output_path: str, video_volume: float = 0.7, music_volume: float = 0.3) -> str: ...
    def fade_in_out(self, input_path: str, output_path: str, fade_in: float = 1.0, fade_out: float = 1.0) -> str: ...
    def add_bass_boost(self, input_path: str, output_path: str, gain: int = 5) -> str: ...
