"""Port for file storage operations."""
from __future__ import annotations
from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class FileStoragePort(Protocol):
    async def save_file(self, content: bytes, filename: str, directory: str = "") -> str: ...
    def get_file_path(self, filename: str, directory: str = "") -> Path: ...
    async def delete_file(self, filepath: str) -> None: ...
    def list_files(self, directory: str = "") -> list[str]: ...
