"""Port for experiment metrics storage (MLflow etc)."""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class MetricsStorePort(Protocol):
    def start_run(self, name: str, tags: dict | None = None) -> str: ...
    def log_metric(self, run_id: str, key: str, value: float, step: int = 0) -> None: ...
    def log_params(self, run_id: str, params: dict) -> None: ...
    def log_artifact(self, run_id: str, filepath: str) -> None: ...
    def end_run(self, run_id: str) -> None: ...
