"""Port for project persistence."""
from __future__ import annotations
from typing import TYPE_CHECKING, Optional, Protocol, runtime_checkable
if TYPE_CHECKING:
    from backend.src.core.entities.project import Project


@runtime_checkable
class ProjectRepositoryPort(Protocol):
    async def save(self, project: Project) -> Project: ...
    async def get_by_id(self, project_id: str) -> Optional[Project]: ...
    async def list_all(self) -> list[Project]: ...
    async def delete(self, project_id: str) -> None: ...
    async def update_status(self, project_id: str, status: str, progress: int = 0) -> None: ...
