"""Port for visual effects operations."""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class VisualEffectsPort(Protocol):
    def apply_color_grading(self, input_path: str, output_path: str, preset: str = "cinematic") -> str: ...
    def apply_vignette(self, input_path: str, output_path: str, intensity: float = 0.3) -> str: ...
    def apply_slow_motion(self, input_path: str, output_path: str, start_time: float = 0.0, end_time: float = 0.0, speed: float = 0.5) -> str: ...
    def apply_transition(self, clip1: str, clip2: str, output_path: str, transition_type: str = "fade", duration: float = 0.5) -> str: ...
